security:
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        facebook_user_provider:
            id: facebook_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/bilemo
            stateless: false
            simple_preauth:
                authenticator: facebook_authenticator
            provider: facebook_user_provider
            logout:
                path:   /bilemo/logout
                target: /

        main:
            anonymous: ~