services:
    facebook_authenticator:
        class: AppBundle\Security\FacebookAuthenticator
        arguments: ["@csa_guzzle.client.facebook_api", "%facebook_client_id%", "%facebook_client_secret%", "@router"]

    facebook_user_provider:
        class: AppBundle\Security\FacebookUserProvider
        arguments: ["@csa_guzzle.client.facebook_api", "@jms_serializer"]
